---
latitude: '49.75542'
longitude: '6.63691'
name: Innisfallen Hotel
email: steffan@traveltripper.io
phone_number: "--"
address:
  street1: Fossa, Killarney
  street2: ''
  state: ''
  city: Co. Kerry
  country: Ireland
  zip_code: V93 CR90
_hotel_id: IRETIK
_portal_id: innisfallenhotel
_root_path: 
logo: <img id="1500302480031" class=" " src="https://s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_120_512/media/2017-07-17-093113/logo.jpg"
  />
