---
latitude: 49.75542
longitude: 6.63691
name: ibis Styles Trier
email: steffan@traveltripper.io
phone_number: "--"
address:
  street1: Metzelstrasse 12
  street2: ''
  state: ''
  city: Trier
  country: 
  zip_code: '54290'
_hotel_id: IRETIK
_portal_id: innisfallenhotel
_root_path: 
logo: <img id="1500302480031" class=" " src="https://s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/1_120_512/media/2017-07-17-093113/logo.jpg"
  />
