---
latitude: 49.75542
longitude: 6.63691
name: ibis Styles Trier
email: steffan@traveltripper.io
phone_number: "--"
address:
  street1: Metzelstrasse 12
  street2: ''
  state: ''
  city: Trier
  country: 
  zip_code: '54290'
_hotel_id: IBI790
_portal_id: required-but-empty
_root_path: https://qa4.ttaws.com/rt
